# -*- coding: utf-8 -*-
"""Investigacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlmh0lqh4kGXfl_btzLvBOpRBzrBxGVD
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # 1. Configuración de la página Web
# st.set_page_config(
#     page_title="Distribución Mapi S.A.C. - Sistema RPA",
#     page_icon="📦",
#     layout="wide"
# )
# 
# # 2. Cargar los datos del archivo Excel real
# @st.cache_data
# def cargar_datos():
#     df = pd.read_excel('01_ENERO-VENTA.xlsx', sheet_name='Informe')
#     return df
# 
# try:
#     df = cargar_datos()
# except Exception as e:
#     st.error(f"Error al cargar el archivo '01_ENERO-VENTA.xlsx'. Asegúrate de que esté en la carpeta de Colab. Detalle: {e}")
#     st.stop()
# 
# # 3. Título del Dashboard
# st.title("📦 Sistema RPA de Control de Inventarios y Distribución")
# st.caption("Distribución Mapi S.A.C. | Demostración de Prototipo Funcional (Enero 2026)")
# 
# # 4. Sidebar / Filtros
# st.sidebar.header("🔍 Filtros de Consulta")
# vendedores = ["Todos"] + list(df['Vendedor'].dropna().unique())
# vendedor_sel = st.sidebar.selectbox("Seleccionar Vendedor / Ruta:", vendedores)
# 
# if vendedor_sel != "Todos":
#     df_filtrado = df[df['Vendedor'] == vendedor_sel]
# else:
#     df_filtrado = df.copy()
# 
# # 5. Tarjetas de KPIs
# st.subheader("📊 Indicadores Clave de Desempeño (KPIs)")
# col1, col2, col3, col4 = st.columns(4)
# 
# with col1:
#     st.metric("Ventas Totales (S/)", f"S/ {df_filtrado['Ventas'].sum():,.2f}")
# with col2:
#     st.metric("Volumen Movilizado", f"{df_filtrado['Cantidad neta'].sum():,.0f} und")
# with col3:
#     st.metric("SKUs Distintos", f"{df_filtrado['CODIGO'].nunique()}")
# with col4:
#     st.metric("Precisión de Stock (Postest Est.)", "99.8%", "▲ +15%")
# 
# st.divider()
# 
# # 6. MÓDULOS DEL BOT RPA
# st.header("🤖 Módulos del Motor RPA (Simulación de Operación)")
# 
# tab1, tab2, tab3 = st.tabs([
#     "🧩 Módulo 1: Conversión Cajas a Salderos",
#     "🏷️ Módulo 2: Picking por Fragilidad",
#     "🚚 Módulo 3: Liquidación de Ruta (Kardex)"
# ])
# 
# # TAB 1: Conversión de Salderos
# with tab1:
#     st.subheader("Algoritmo de Conversión Automática de Pedidos")
#     st.write("Calcula la cantidad de cajas cerradas y unidades sueltas (salderos) para evitar aperturas no registradas en almacén.")
# 
#     col_a, col_b = st.columns(2)
#     with col_a:
#         sku_demo = st.selectbox("Seleccionar Producto para Prueba:", df['Producto'].dropna().unique()[:10])
#         cant_pedida = st.number_input("Cantidad pedida por el cliente (Unidades):", min_value=1, value=75)
#         caja_factor = st.number_input("Factor de empaque (Unidades por caja):", min_value=1, value=48)
# 
#     with col_b:
#         cajas_completas = cant_pedida // caja_factor
#         unidades_sueltas = cant_pedida % caja_factor
# 
#         st.success("✅ **Resultado del Procesamiento RPA:**")
#         st.write(f"• **Cajas Cerradas a Despachar:** {cajas_completas} caja(s)")
#         st.write(f"• **Unidades en Zona de Salderos:** {unidades_sueltas} unidad(es)")
#         st.info(f"💡 *Ajuste automático en Kardex: Se descuenta {cajas_completas} cj del inventario general y {unidades_sueltas} und del stock de picking.*")
# 
# # TAB 2: Priorización por Fragilidad
# with tab2:
#     st.subheader("Clasificación de Empaque para Optimización de Carga")
#     st.write("Genera la secuencia de apilamiento en el camión para mitigar la tasa de mermas.")
# 
#     df_fragil = df_filtrado.copy()
#     def clasificar_fragilidad(cat):
#         cat_str = str(cat).lower()
#         if 'chocolates' in cat_str or 'bizcochos' in cat_str:
#             return '3 - Fragilidad Alta (Apilar Arriba)'
#         elif 'galletas' in cat_str or 'caramelos' in cat_str:
#             return '2 - Fragilidad Media (Zona Media)'
#         else:
#             return '1 - Resistente / Pesado (Base del Vehículo)'
# 
#     df_fragil['Nivel Fragilidad'] = df_fragil['Categoria'].apply(clasificar_fragilidad)
# 
#     fig = px.bar(
#         df_fragil.groupby('Nivel Fragilidad')['Cantidad neta'].sum().reset_index(),
#         x='Nivel Fragilidad',
#         y='Cantidad neta',
#         color='Nivel Fragilidad',
#         title="Volumen a Cargar por Nivel de Fragilidad de Empaque"
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
# # TAB 3: Liquidación de Ruta y Kardex
# with tab3:
#     st.subheader("Conciliación de Devoluciones y Eliminación de Inventario Fantasma")
#     st.write("Registra los rechazos en ruta el mismo día mediante la API de WhatsApp.")
# 
#     col_x, col_y = st.columns(2)
#     with col_x:
#         st.text_input("N° Guía / Boleta:", "BOL-2026-0849")
#         st.selectbox("Causa de Incidencia:", ["Cliente Rechazó Pedido", "Producto Dañado en Ruta", "Diferencia de Precio"])
#         monto_devuelto = st.number_input("Monto Afectado (S/):", min_value=0.0, value=125.50)
# 
#     with col_y:
#         if st.button("🚀 Procesar Conciliación con Bot RPA"):
#             st.balloons()
#             st.success("✅ **Liquidación Exitosa:**")
#             st.write("1. Kardex actualizado en tiempo real.")
#             st.write("2. Nota de Crédito generada en PDF.")
#             st.write("3. Notificación enviada al cliente por WhatsApp.")
#             st.write("4. Inventario Fantasma eliminado.")
# 
# st.divider()
# 
# # 7. Tabla Transaccional
# st.subheader("📋 Registro de Ventas Analizado")
# st.dataframe(df_filtrado[['Vendedor', 'Categoria', 'CODIGO', 'Producto', 'Ventas', 'Cantidad neta']].head(50), use_container_width=True)
